# -*- coding: utf-8 -*-
"""Face Emotion detection webcam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvyDng1kcQmfkuo9hGJSABy2rjw2sMSv
"""

!nvidia-smi

!pip install ultralytics

import ultralytics
ultralytics.checks()

from ultralytics import YOLO
from IPython.display import Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="ekWNOMr3uNsNsfjMo0Sr")
project = rf.workspace("spacex-bmpib").project("emotion-gyup3")
version = project.version(8)
dataset = version.download("yolov11")

dataset.location

!yolo task=detect mode=train data={dataset.location}/data.yaml model="yolo11n.pt" epochs=5 imgsz=640

!yolo task=detect mode=predict model= "/content/runs/detect/train/weights/best.pt" conf=0.25 source=/content/ChatGPT.jpg save=True

!yolo task=detect mode=predict model= "/content/runs/detect/train/weights/best.pt" conf=0.25 source=/content/pexels.jpg save=True